# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
