# Generated by Django 2.0.1 on 2018-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180224_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
