# Generated by Django 2.0.1 on 2018-02-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
